export const REQUEST_NEWS = 'REQUEST_NEWS';
export const RECEIVE_NEWS = 'RECEIVE_NEWS';
export const FAIL_GETTING_NEWS = 'FAIL_GETTING_NEWS';
export const GET_PARAM_NEWS = 'GET_PARAM_NEWS';
export const GET_TOTAL_RESULTS_NEWS = 'GET_TOTAL_RESULTS_NEWS';